wandb_version: 1

learning_rate:
  desc: null
  value: 0.005
architecture:
  desc: null
  value: Orignal_ResNet
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715930619.0
    t:
      1:
      - 1
      - 41
      - 49
      - 51
      - 55
      - 105
      2:
      - 1
      - 41
      - 49
      - 51
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.4
      8:
      - 1
      - 5
      13: linux-x86_64
